Movie_webapp/movie_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from movie_website import views
urlpatterns = [
    path('', include('movie_website.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^avatar/(?P<path>.*)/$', serve, {"document_root": settings.MEDIA_ROOT}),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Movie_webapp/movie_website/urls.py
from django.contrib import admin
from django.urls import path, re_path

from movie_website import views
from django.conf import settings



app_name = "movie_website"
urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login),
    path('register/', views.register),
    path('logout/', views.logout),
    path('detail/<int:movie_no>', views.detail, name='detail'),
    path('action/', views.action_filter, name='action'),
    path('drama/', views.drama_filter, name='drama'),
    path('crime/', views.crime_filter, name='crime'),
    path('fantasy/', views.fantasy_filter, name='fantasy'),
    path('top10/', views.top_10, name='top10'),
    path('upload/', views.upload, name='upload'),
    path('order/', views.place_order, name='order'),
    path('order_status/', views.order_status, name='order_status'),
    path('findpwdView/', views.findpwdView),
    path('forgotPwd/', views.forgotPwd),
    path('ratings/', views.rating),
]

Movie_webapp/movie_website/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.core.validators import MaxValueValidator


# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    c_time = models.DateTimeField(auto_now_add=True)
    avatar = models.ImageField(upload_to='avatar', default='', verbose_name='avatar')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-c_time"]
        verbose_name = "user"
        verbose_name_plural = "user"


class Writer(models.Model):
    name = models.CharField(max_length=300, verbose_name='Writer_name')

    def __str__(self):
        return self.name


class SoundSection(models.Model):
    artist_name = models.CharField(max_length=300, db_index=True)
    artist_type = models.CharField(max_length=300)

    def __str__(self):
        return self.artist_name + ' : ' + self.artist_type


class Cast(models.Model):
    name = models.CharField(max_length=400, verbose_name='Cast_name')

    def __str__(self):
        return self.name


class Director(models.Model):
    name = models.CharField(max_length=400, verbose_name='Director_name')

    def __str__(self):
        return self.name


class Producer(models.Model):
    name = models.CharField(max_length=400, verbose_name='Producer_name')

    def __str__(self):
        return self.name


class Musician(models.Model):
    name = models.CharField(max_length=400, verbose_name='Musician_name')

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=400, verbose_name='Genre_name')

    def __str__(self):
        return self.name


class Movie(models.Model):
    # page one features
    title = models.CharField(max_length=200, verbose_name='Movie Title')
    description = models.CharField(max_length=500, verbose_name='Description')
    rating = models.DecimalField(max_length=500, decimal_places=2, max_digits=4, verbose_name='Rating')
    # page two features
    image_url = models.CharField(max_length=1000, verbose_name='Image Link', default='')
    duration = models.CharField(max_length=200, verbose_name='Duration')
    year = models.CharField(max_length=500, verbose_name='Year')
    writers = models.ManyToManyField(Writer)
    director = models.ManyToManyField(Director)
    producer = models.ManyToManyField(Producer)
    cast = models.ManyToManyField(Cast)
    sounds = models.ManyToManyField(SoundSection, blank=True)
    musician = models.ManyToManyField(Musician)
    genre = models.ManyToManyField(Genre)
    number = models.IntegerField(default=100,verbose_name='Total Number of Rating')
    latest = models.PositiveIntegerField(validators=[MaxValueValidator(10)], null=True, verbose_name='Latest User Rating')

    def __str__(self):
        return self.title


class Orders(models.Model):
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    movie_name = models.CharField(max_length=100, verbose_name='Movie Name')
    order_date = models.DateField()
    order_status = models.CharField(max_length=100,verbose_name='status')

Movie_webapp/movie_website/forms.py
from django import forms
from .models import User

class UserForm(forms.Form):
    username = forms.CharField(label="Username", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Username", 'autofocus': ''}))
    password = forms.CharField(label="Password", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': "Password"}))


class RegisterForm(forms.Form):
    username = forms.CharField(label="username", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="email", widget=forms.EmailInput(attrs={'class': 'input_form'}))
    password1 = forms.CharField(label="password", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="password", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class OrderMovieForm(forms.Form):
    title = forms.CharField(label="Movie Name", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))

Movie_webapp/movie_website/views.py
import random
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse, JsonResponse
from . import models
from . import forms
import logging
import threading
import datetime
import requests
import json
from django.shortcuts import get_object_or_404
from .models import Movie, Orders, User, Genre, Director, Cast, Writer
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail
from movie_project.settings import EMAIL_HOST_USER
import decimal


def index(request):
    # 如果登陆了就显示用户名，不然就显示Login
    if request.session.get('is_login', None):
        username = request.session['user_name']
    else:
        username = 'Login'
    movie_list = Movie.objects.all()
    return render(request, 'login/index.html', {'movie_list': movie_list})


def login(request):
    # 不允许重复登陆
    if request.session.get('is_login', None):
        return redirect('/')
    if request.method == "POST":
        # 实例
        login_form = forms.UserForm(request.POST)
        message = 'Check your username or password'
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            try:
                user = models.User.objects.get(name=username)
            except:
                message = 'User does not exist!'
                # 使用locals代替{'message': message}
                return render(request, 'login/login.html', locals())

            if user.password == password:
                # 可以往里面写任何数据，不限于用户相关
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.name
                # request.session.set_expiry()
                return redirect('/index/')
            else:
                message = 'Password incorrect'
                return render(request, 'login/login.html', locals())

        else:
            return render(request, 'login/login.html', locals())

    login_form = forms.UserForm()
    return render(request, 'login/login.html', locals())


def register(request):
    if request.session.get('is_login', None):
        return redirect('/index/')

    if request.method == 'POST':
        register_form = forms.RegisterForm(request.POST)
        message = "Check your input！"
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username')
            password1 = register_form.cleaned_data.get('password1')
            password2 = register_form.cleaned_data.get('password2')
            email = register_form.cleaned_data.get('email')

            if password1 != password2:
                message = 'Wrong password'
                return render(request, 'login/register.html', locals())
            else:
                same_name_user = models.User.objects.filter(name=username)
                if same_name_user:
                    message = 'Username already exists'
                    return render(request, 'login/register.html', locals())
                same_email_user = models.User.objects.filter(email=email)
                if same_email_user:
                    message = 'Email already exists！'
                    return render(request, 'login/register.html', locals())

                new_user = models.User()
                new_user.name = username
                new_user.password = password1
                new_user.email = email
                new_user.save()

                return redirect('/login/')
        else:
            return render(request, 'login/register.html', locals())
    register_form = forms.RegisterForm()
    return render(request, 'login/register.html', locals())


def logout(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/login/")
    request.session.flush()
    # 或者使用下面的方法
    # del request.session['is_login']
    # del request.session['user_id']
    # del request.session['user_name']
    return redirect("/login/")

def check_db(name):
    result = True
    try:
        res = Movie.objects.get(title=name)
    except ObjectDoesNotExist:
        result = False
    return result


def check_presence(type, name):
    result = None
    try:
        result = type.objects.get(name=name)
    except ObjectDoesNotExist:
        result = None
    return result


def get_movie(title):
    url = "http://www.omdbapi.com/?apikey=40024d7d&"

    querystring = {"t": str(title)}

    response = requests.request("GET", url, params=querystring)

    return response.text


def fetch_and_store(title, user_id):
    movie_data = get_movie(title)
    logger = logging.getLogger(__name__)
    json_data = json.loads(movie_data)
    logger.info(json_data)
    movie = Movie()
    movie.title = json_data['Title']
    movie.description = json_data['Plot']
    movie.duration = json_data['Runtime']
    movie.image_url = json_data['Poster']
    movie.rating = json_data['imdbRating']
    movie.year = str(json_data['Released'])[-4:]
    movie.save()
    res = check_presence(Director, json_data['Director'])
    if res is None:
        direct = Director()
        direct.name = json_data['Director']
        direct.save()
        movie.director.add(direct)
    else:
        movie.director.add(res)
    genres = str(json_data['Genre']).split(', ')
    for genre_name in genres:
        res = check_presence(Genre, genre_name)
        if res is None:
            gen = Genre()
            gen.name = genre_name
            gen.save()
            movie.genre.add(gen)
        else:
            movie.genre.add(res)
    writers = str(json_data['Writer']).split(', ')
    for writer_name in writers:
        res = check_presence(Writer, writer_name)
        if res is None:
            writ = Writer()
            writ.name = writer_name
            writ.save()
            movie.writers.add(writ)
        else:
            movie.writers.add(res)
    cast_names = str(json_data['Actors']).split(', ')
    for cast_name in cast_names:
        res = check_presence(Cast, cast_name)
        if res is None:
            actor = Cast()
            actor.name = cast_name
            actor.save()
            movie.cast.add(actor)
        else:
            movie.cast.add(res)
    order = Orders.objects.get(user_id=user_id, movie_name=movie.title)
    order.order_status = "Completed";
    order.save()


def place_order(request):
    if request.session.get('is_login', None):
        if request.method == 'POST':
            order_form = forms.OrderMovieForm(request.POST)
            if order_form.is_valid():
                title = order_form.cleaned_data.get('title')
                if check_db(title):
                    message = "unsuccess"
                    return render(request, 'login/status.html', locals())
                else:
                    order = Orders()
                    usr_id = request.session['user_id']
                    order.user_id = User.objects.get(id=usr_id)
                    order.order_status = "In Progress"
                    order.order_date = datetime.date.today()
                    order.movie_name = title
                    order.save()
                    message = "success"
                    fetch = threading.Thread(target=fetch_and_store(title, usr_id), args=(1,))
                    fetch.start()
                    return render(request, 'login/status.html', locals())

        order_form = forms.OrderMovieForm()
        return render(request, 'login/order.html', locals())


def order_status(request):
    if request.session.get('is_login', None):
        usr_id = request.session['user_id']
        orders = Orders.objects.filter(user_id=usr_id)
        return render(request, 'login/order_status.html', locals())

def detail(request, movie_no):
    # remain the state
    if request.session.get('is_login', None):
        username = request.session['user_name']
    else:
        username = 'Login'

    movie = get_object_or_404(Movie, id=movie_no)
    return render(request, 'login/detail.html', locals())


def action_filter(request):
    if request.session.get('is_login', None):
        username = request.session['user_name']
    else:
        username = 'Login'
    movie_list = Movie.objects.filter(genre__name='Action')
    return render(request, 'login/index.html', {'movie_list': movie_list})


def crime_filter(request):
    if request.session.get('is_login', None):
        username = request.session['user_name']
    else:
        username = 'Login'
    movie_list = Movie.objects.filter(genre__name='Crime')
    return render(request, 'login/index.html', {'movie_list': movie_list})


def fantasy_filter(request):
    if request.session.get('is_login', None):
        username = request.session['user_name']
    else:
        username = 'Login'
    movie_list = Movie.objects.filter(genre__name='Fantasy')
    return render(request, 'login/index.html', {'movie_list': movie_list})


def drama_filter(request):
    if request.session.get('is_login', None):
        username = request.session['user_name']
    else:
        username = 'Login'
    movie_list = Movie.objects.filter(genre__name='Drama')
    return render(request, 'login/index.html', {'movie_list': movie_list})


def top_10(request):
    if request.session.get('is_login', None):
        username = request.session['user_name']
    else:
        username = 'Login'
    movie_list = Movie.objects.all().order_by('-rating')[:10]
    return render(request, 'login/index.html', {'movie_list': movie_list})


def upload(request):
    if request.session.get('is_login', None):
        if request.method == 'POST' and request.FILES['upload']:
            upload = request.FILES['upload']
            fss = FileSystemStorage()
            file = fss.save(upload.name, upload)
            file_url = fss.url(file)

Movie_webapp/movie_website/templates/login/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Movie Website</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="../../static/login/css/bootstrap.min.css">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="../../static/login/css/style.css">
      <!-- Responsive-->
      <link rel="stylesheet" href="../../static/login/css/responsive.css">
      <!-- fevicon -->
      <link rel="icon" href="../login/static/images/fevicon.png" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="../../static/login/css/jquery.mCustomScrollbar.min.css">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="../../static/login/css/font-awesome.css">
      <!-- owl stylesheets -->
      <link rel="stylesheet" href="../../static/login/css/owl.carousel.min.css">
      <link rel="stylesheet" href="../login/static/css/owl.theme.default.min.css">
      <link rel="stylesheet" href="../../static/login/css/jquery.fancybox.min.css" media="screen">
      <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
   </head>
   <body>
      <!-- header section start -->
      <div class="header_section">
         <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="logo" href="index.html"><img src="../../static/login/images/logo.png"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

{#             nav section                  ----------------------------------#}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
               <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                     <a class="nav-link" href="{% url 'movie_website:index' %}">Home</a>
                  </li>
                   <li class="nav-item active"><a class="nav-link" href = "{% url 'movie_website:crime'%}">Crime</a></li>
                  <li class="nav-item active"><a class="nav-link" href = "{% url 'movie_website:action'%}">Action</a></li>
                  <li class="nav-item active"><a class="nav-link" href = "{% url 'movie_website:drama'%}">Drama</a></li>
                  <li class="nav-item active"><a class="nav-link" href = "{% url 'movie_website:fantasy'%}">Fantasy</a></li>
                  <li class="nav-item active"><a class="nav-link" href = "{% url 'movie_website:top10'%}">Top 10</a></li>
               </ul>
                {% if request.session.is_login %}
{#                    <p>{{ request.user.is_authenticated}}</p>#}
                    <div class="dropdown nav_dropdown">
                        <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-expanded="false">
                        {{ username }}
                        </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/order_status">My Orders</a>
                        <a class="dropdown-item" href="/order">Order Movie</a>
                        <a class="dropdown-item" href="/logout">Logout</a>
                        <a class="dropdown-item" href="/upload">Change Avatar</a>
                    </div>
                    </div>
                {% else %}
{#                    <p>{{ request.user.is_authenticated}}</p>#}
                     <div class="dropdown nav_dropdown">
                         <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-expanded="false">
                        😊
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                         <a class="dropdown-item" href="/login">Login</a>
                        <a class="dropdown-item" href="/register">Register</a>
                    </div>
                    </div>
                {% endif %}

            </div>
         </nav>
      </div>

{% block body_block %}*** {% endblock %}
{#      <div class="footer_section ">#}
{#         <div class="container">#}
{#            <div class="footer_menu">#}
{#               <ul>#}
{#               </ul>#}
{#            </div>#}
{#            <div class="social_icon">#}
{#               <ul>#}
{#                  <li><a href="#"><img src="../../static/login/images/fb-icon.png"></a></li>#}
{#                  <li><a href="#"><img src="../../static/login/images/twitter-icon.png"></a></li>#}
{#                  <li><a href="#"><img src="../../static/login/images/linkedin-icon.png"></a></li>#}
{#                  <li><a href="#"><img src="../../static/login/images/instagram-icon.png"></a></li>#}
{#               </ul>#}
{#            </div>#}
{#         </div>#}
{#      </div>#}
      <!-- footer  section end -->
      <!-- copyright section start -->
{#      <div class="copyright_section">#}
{#         <div class="container">#}
{#            <div class="copyright_text">Copyright &copy; 2020.Company name All rights reserved.<a target="_blank" href="http://sc.chinaz.com/moban/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></div>#}
{#         </div>#}
{#      </div>#}
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="../../static/login/js/jquery.min.js"></script>
      <script src="../../static/login/js/popper.min.js"></script>
      <script src="../../static/login/js/bootstrap.bundle.min.js"></script>
      <script src="../../static/login/js/jquery-3.0.0.min.js"></script>
      <!-- sidebar -->
      <script src="../../static/login/js/jquery.mCustomScrollbar.concat.min.js"></script>
      <!-- javascript -->
      <script src="../../static/login/js/jquery.fancybox.min.js"></script>
      <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
      <script>
         $('#datepicker').datepicker({
             uiLibrary: 'bootstrap4'
         });
      </script>
   </body>
</html>

Movie_webapp/movie_website/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
{#      <meta charset="utf-8">#}
{#      <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#      <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#      <!-- mobile metas -->#}
{#      <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#      <meta name="viewport" content="initial-scale=1, maximum-scale=1">#}
      <!-- site metas -->
      <title>Movie Website</title>
{#      <meta name="keywords" content="">#}
{#      <meta name="description" content="">#}
{#      <meta name="author" content="">#}
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="../../static/login/css/bootstrap.min.css">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="../../static/login/css/style.css">
{#      <!-- Responsive-->#}
{#      <link rel="stylesheet" href="../../static/login/css/responsive.css">#}
{#      <!-- fevicon -->#}
{#      <link rel="icon" href="../login/static/images/fevicon.png" type="image/gif" />#}
{#      <!-- Scrollbar Custom CSS -->#}
{#      <link rel="stylesheet" href="../../static/login/css/jquery.mCustomScrollbar.min.css">#}
{#      <!-- Tweaks for older IEs-->#}
{#      <link rel="stylesheet" href="../../static/login/css/font-awesome.css">#}
{#      <!-- owl stylesheets --> #}
{#      <link rel="stylesheet" href="../../static/login/css/owl.carousel.min.css">#}
{#      <link rel="stylesheet" href="../login/static/css/owl.theme.default.min.css">#}
{#      <link rel="stylesheet" href="../../static/login/css/jquery.fancybox.min.css" media="screen">#}
{#      <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />#}
   </head>
   <body>
      <!-- header section start -->
      <div class="header_section">
         <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="logo" href="index.html"><img src="../../static/login/images/logo.png"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

{#             nav section                  ----------------------------------#}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
               <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                     <a class="nav-link" href="{% url 'movie_website:index' %}">Home</a>
                  </li>
                   <li class="nav-item active"><a class="nav-link" href = "{% url 'movie_website:crime'%}">Crime</a></li>
                  <li class="nav-item active"><a class="nav-link" href = "{% url 'movie_website:action'%}">Action</a></li>
                  <li class="nav-item active"><a class="nav-link" href = "{% url 'movie_website:drama'%}">Drama</a></li>
                  <li class="nav-item active"><a class="nav-link" href = "{% url 'movie_website:fantasy'%}">Fantasy</a></li>
                  <li class="nav-item active"><a class="nav-link" href = "{% url 'movie_website:top10'%}">Top 10</a></li>
               </ul>
                {% if request.session.is_login %}
{#                    <p>{{ request.user.is_authenticated}}</p>#}
                    <div class="dropdown nav_dropdown">
                        <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-expanded="false">
                        {{ username }}
                        </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/order_status">My Orders</a>
                        <a class="dropdown-item" href="/order">Order Movie</a>
                        <a class="dropdown-item" href="/logout">Logout</a>
                        <a class="dropdown-item" href="/upload">Change Avatar</a>
                    </div>
                    </div>
                {% else %}
{#                    <p>{{ request.user.is_authenticated}}</p>#}
                     <div class="dropdown nav_dropdown">
                         <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-expanded="false">
                        😊
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                         <a class="dropdown-item" href="/login">Login</a>
                        <a class="dropdown-item" href="/register">Register</a>
                    </div>
                    </div>
                {% endif %}

            </div>
         </nav>
      </div>

<div class="movies_section">
         <div class="container">
            <div class="movies_section_2 layout_padding">
               <h2 class="letest_text">Movies</h2>
               <section class="movies_main">
                  <section id ="mov-list">
                      {% for movie in movie_list %}
                          <div class="col-md-3">
                          <div class="iamge_movies">
                                <li><a href="{% url 'movie_website:detail' movie.id%}"><img src={{ movie.image_url }} ></a></li>

                          </div>
                              <li><a href="{% url 'movie_website:detail' movie.id%}"><h1 class="code_text">{{ movie.title}}</h1></a></li>
                          </div>
                      {% endfor %}
                  </section>
               </section>
                  </div>
               </div>
            </div>


      <div class="footer_section layout_padding">
         <div class="container">
            <div class="footer_menu">
               <ul>
               </ul>
            </div>
            <div class="social_icon">
               <ul>
                  <li><a href="#"><img src="../../static/login/images/fb-icon.png"></a></li>
                  <li><a href="#"><img src="../../static/login/images/twitter-icon.png"></a></li>
                  <li><a href="#"><img src="../../static/login/images/linkedin-icon.png"></a></li>
                  <li><a href="#"><img src="../../static/login/images/instagram-icon.png"></a></li>
               </ul>
            </div>
         </div>
      </div>
      <!-- footer  section end -->
      <!-- copyright section start -->
      <div class="copyright_section">
         <div class="container">
            <div class="copyright_text">Copyright &copy; 2020.Company name All rights reserved.<a target="_blank" href="http://sc.chinaz.com/moban/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></div>
         </div>
      </div>
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="../../static/login/js/jquery.min.js"></script>
      <script src="../../static/login/js/popper.min.js"></script>
      <script src="../../static/login/js/bootstrap.bundle.min.js"></script>
      <script src="../../static/login/js/jquery-3.0.0.min.js"></script>
      <!-- sidebar -->
      <script src="../../static/login/js/jquery.mCustomScrollbar.concat.min.js"></script>
      <script src="../../static/login/js/custom.js"></script>
      <!-- javascript --> 
      <script src="../login/static/js/owl.carousel.js"></script>
      <script src="../../static/login/js/jquery.fancybox.min.js"></script>
      <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
      <script>
         $('#datepicker').datepicker({
             uiLibrary: 'bootstrap4'
         });
      </script>
   </body>
</html>